[START][2024-01-21 21:14:43] LSP logging initiated
[ERROR][2024-01-21 21:14:43] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:43,647 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:48] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:48,533 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:50] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:50,242 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:50] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:50,867 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:51] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:51,232 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:51] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:51,575 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:51] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:51,875 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:53] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:53,129 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:53] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:53,798 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:54] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:54,403 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:05,305 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:06] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:06,807 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:07] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:07,721 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:11] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:11,175 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:14] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:14,201 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:14] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:14,862 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[START][2024-01-21 21:21:32] LSP logging initiated
[ERROR][2024-01-21 21:21:32] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-21 21:21:32,165 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-21 21:21:33] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-21 21:21:33,173 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-21 21:21:34] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-21 21:21:34,188 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
