[START][2024-01-21 21:14:43] LSP logging initiated
[ERROR][2024-01-21 21:14:43] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:43,647 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:48] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:48,533 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:50] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:50,242 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:50] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:50,867 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:51] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:51,232 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:51] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:51,575 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:51] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:51,875 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:53] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:53,129 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:53] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:53,798 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:14:54] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:14:54,403 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:05] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:05,305 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:06] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:06,807 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:07] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:07,721 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:11] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:11,175 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:14] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:14,201 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[ERROR][2024-01-21 21:15:14] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-21 21:15:14,862 Central Europe Standard Time - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: `line` parameter is not in a valid range.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\config\\config.py\", line 39, in _hookexec\r\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 457, in traced_hookexec\r\n    return outcome.get_result()\r\n           ^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 114, in get_result\r\n    raise exc.with_traceback(exc.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_result.py\", line 76, in from_call\r\n    result = func()\r\n             ^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_manager.py\", line 454, in <lambda>\r\n    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 113, in _multicall\r\n    raise exception.with_traceback(exception.__traceback__)\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\r\n    res = hook_impl.function(*args)\r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\plugins\\jedi_completion.py\", line 46, in pylsp_completions\r\n    completions = document.jedi_script(use_document_path=True).complete(**code_position)\r\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\jedi\\api\\helpers.py\", line 473, in wrapper\r\n    raise ValueError('`line` parameter is not in a valid range.')\r\nValueError: `line` parameter is not in a valid range.\r\n"
[START][2024-01-21 21:21:32] LSP logging initiated
[ERROR][2024-01-21 21:21:32] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-21 21:21:32,165 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-21 21:21:33] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-21 21:21:33,173 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-21 21:21:34] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-21 21:21:34,188 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[START][2024-01-22 22:04:47] LSP logging initiated
[ERROR][2024-01-22 22:04:47] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-22 22:04:47,449 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[START][2024-01-22 23:20:18] LSP logging initiated
[ERROR][2024-01-22 23:20:18] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-22 23:20:18,238 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-22 23:20:19] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-22 23:20:19,248 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-22 23:20:20] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-22 23:20:20,257 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[START][2024-01-23 22:28:50] LSP logging initiated
[ERROR][2024-01-23 22:28:50] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-23 22:28:50,849 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-23 22:28:51] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-23 22:28:51,877 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-23 22:28:52] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-23 22:28:52,888 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[START][2024-01-23 22:51:47] LSP logging initiated
[ERROR][2024-01-23 22:51:47] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-23 22:51:47,752 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-23 22:51:48] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-23 22:51:48,760 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[WARN][2024-01-23 22:59:35] .../lua/vim/lsp.lua:1636	"buf_attach_client called on unloaded buffer (id: 5): "
[ERROR][2024-01-23 23:08:19] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-23 23:08:19,850 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-23 23:27:44] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-23 23:27:44,862 Central Europe Standard Time - WARNING - pylsp._utils - Path c:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\ntpath.py not in d:\\_coding\\python-course\r\n"
[ERROR][2024-01-23 23:27:45] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-23 23:27:45,501 Central Europe Standard Time - WARNING - pylsp._utils - Path c:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\ntpath.py not in d:\\_coding\\python-course\r\n"
[ERROR][2024-01-23 23:28:12] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-23 23:28:12,846 Central Europe Standard Time - WARNING - pylsp._utils - Path c:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\posixpath.py not in d:\\_coding\\python-course\r\n"
[ERROR][2024-01-23 23:28:13] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-23 23:28:13,365 Central Europe Standard Time - WARNING - pylsp._utils - Path c:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\posixpath.py not in d:\\_coding\\python-course\r\n"
[ERROR][2024-01-23 23:28:55] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-23 23:28:55,305 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[START][2024-01-23 23:31:22] LSP logging initiated
[ERROR][2024-01-23 23:31:22] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-23 23:31:22,236 Central Europe Standard Time - WARNING - pylsp._utils - Path c:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\os.py not in d:\\_coding\\python-course\r\n"
[ERROR][2024-01-23 23:31:22] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-23 23:31:22,766 Central Europe Standard Time - WARNING - pylsp._utils - Path c:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\os.py not in d:\\_coding\\python-course\r\n"
[START][2024-01-24 18:56:43] LSP logging initiated
[ERROR][2024-01-24 18:56:43] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-24 18:56:43,431 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 55\r\n"
[ERROR][2024-01-24 19:05:28] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 19:05:28,106 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-24 20:25:43] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 20:25:43,866 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-24 20:25:44] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 20:25:44,876 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-24 20:25:45] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 20:25:45,891 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-24 20:25:53] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 20:25:53,812 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[WARN][2024-01-24 20:31:52] .../lua/vim/lsp.lua:1636	"buf_attach_client called on unloaded buffer (id: 4): "
[START][2024-01-24 21:54:34] LSP logging initiated
[ERROR][2024-01-24 21:54:34] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 21:54:34,024 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-24 21:54:35] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 21:54:35,049 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[WARN][2024-01-24 21:59:33] .../lua/vim/lsp.lua:1636	"buf_attach_client called on unloaded buffer (id: 4): "
[START][2024-01-24 22:20:07] LSP logging initiated
[ERROR][2024-01-24 22:20:07] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-24 22:20:07,509 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 2\r\n"
[ERROR][2024-01-24 22:36:33] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-24 22:36:33,937 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[START][2024-01-24 23:05:21] LSP logging initiated
[WARN][2024-01-24 23:05:21] .../lua/vim/lsp.lua:101	"method workspace/symbol is not supported by any of the servers registered for the current buffer"
[START][2024-01-25 18:44:55] LSP logging initiated
[ERROR][2024-01-25 18:44:55] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-25 18:44:55,845 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[START][2024-01-27 09:32:10] LSP logging initiated
[WARN][2024-01-27 09:32:10] .../lua/vim/lsp.lua:1636	"buf_attach_client called on unloaded buffer (id: 10): "
[START][2024-01-28 23:17:49] LSP logging initiated
[WARN][2024-01-28 23:17:49] .../lua/vim/lsp.lua:1636	"buf_attach_client called on unloaded buffer (id: 7): "
[START][2024-01-29 18:53:59] LSP logging initiated
[ERROR][2024-01-29 18:53:59] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-29 18:53:59,705 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-29 19:04:02] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 19:04:02,583 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 95\r\n"
[ERROR][2024-01-29 19:04:03] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 19:04:03,181 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 98\r\n"
[ERROR][2024-01-29 19:04:03] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 19:04:03,250 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 99\r\n"
[ERROR][2024-01-29 19:04:03] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 19:04:03,359 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 100\r\n"
[ERROR][2024-01-29 20:29:47] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 20:29:47,046 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 104\r\n"
[WARN][2024-01-29 20:46:14] .../lua/vim/lsp.lua:1636	"buf_attach_client called on unloaded buffer (id: 7): "
[START][2024-01-29 21:59:39] LSP logging initiated
[ERROR][2024-01-29 21:59:39] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2024-01-29 21:59:39,166 Central Europe Standard Time - WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.\r\nTraceback (most recent call last):\r\n  File "C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\Lib\\site-packages\\pylsp\\workspace.py", line 252, in _progress_begin\r\n    ).result(timeout=1.0)\r\n      ^^^^^^^^^^^^^^^^^^^\r\n  File "C:\\Users\\krali\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py", line 458, in result\r\n    raise TimeoutError()\r\nTimeoutError\r\n'
[ERROR][2024-01-29 22:03:25] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 22:03:25,592 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 34\r\n"
[ERROR][2024-01-29 22:05:08] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 22:05:08,975 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 49\r\n"
[ERROR][2024-01-29 22:05:09] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\krali\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	"2024-01-29 22:05:09,556 Central Europe Standard Time - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 51\r\n"
[WARN][2024-01-29 23:14:21] .../lua/vim/lsp.lua:1636	"buf_attach_client called on unloaded buffer (id: 8): "
